dist: xenial
sudo: required
language: node_js
node_js: 6
cache:
  directories:
  - node_modules

services:
- docker

before_install: docker pull malept/electron-forge-container
script:
- sudo docker run --privileged --interactive --tty --volume $(pwd):/code malept/electron-forge-container:latest /bin/bash -c "flatpak install --user --no-deps --assumeyes --arch i386 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref &&
    flatpak install --user --no-deps --assumeyes --arch i386 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref &&
    flatpak install --user --no-deps --assumeyes --arch i386 --from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref &&
    cd /code &&
    DEBUG=electron-installer-flatpak,flatpak-bundler npm test"
