dist: xenial
language: node_js
node_js: 8
cache:
  npm: true
  directories:
  - $HOME/.local/share/flatpak

env:
  global:
  - DEBUG: "@malept/flatpak-bundler"

before_install:
- sudo add-apt-repository -y ppa:alexlarsson/flatpak
- sudo apt update
- sudo apt install --no-install-recommends -y flatpak-builder
- ./test/install_runtimes.sh

install:
- npm install
- npm update
